#!/usr/bin/env python3
# from typing import *
import itertools

YES = 'Yes'
NO = 'No'


# def solve(N: int, S: List[str]) -> str:
def solve(N, S):
    for i in range(N):
        for j in range(N):
            if i == j:
                continue
            tmp = S[i] + S[j]
            if len(tmp) % 2 == 0:
                num = len(tmp)//2
                a = list(tmp[:num])
                b = list(reversed(tmp[num:]))
            else:
                num = (len(tmp) - 1) // 2
                a = list(tmp[:num])
                b = list(reversed(tmp[num+1:]))
            # print(tmp)
            # print(a)
            # print(b)
            if a == b:
                return YES
    return NO

    # for tmp in itertools.combinations(S, 2):
    #     print(tmp)
    # return YES


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    S = [None for _ in range(N)]
    for i in range(N):
        S[i] = input()
    a = solve(N, S)
    print(a)


if __name__ == '__main__':
    main()
