#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 1000)  # TODO: edit here
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    M = random.randint(1, 1000)  # TODO: edit here
    B = [None for _ in range(M)]
    for i in range(M):
        B[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    L = random.randint(1, 1000)  # TODO: edit here
    C = [None for _ in range(L)]
    for i in range(L):
        C[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    Q = random.randint(1, 1000)  # TODO: edit here
    X = [None for _ in range(Q)]
    for i in range(Q):
        X[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    print(N)
    print(*[A[i] for i in range(N)])
    print(M)
    print(*[B[i] for i in range(M)])
    print(L)
    print(*[C[i] for i in range(L)])
    print(Q)
    print(*[X[i] for i in range(Q)])

if __name__ == "__main__":
    main()
