#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const std::string YES = "Yes";
const std::string NO = "No";
auto solve(int N, const std::vector<int64_t> &A, int M, const std::vector<int64_t> &B, int L, const std::vector<int64_t> &C, int Q, const std::vector<int64_t> &X) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N, M, L, Q;
    std::cin >> N;
    std::vector<int64_t> A(N);
    REP (i, N) {
        std::cin >> A[i];
    }
    std::cin >> M;
    std::vector<int64_t> B(M);
    REP (i, M) {
        std::cin >> B[i];
    }
    std::cin >> L;
    std::vector<int64_t> C(L);
    REP (i, L) {
        std::cin >> C[i];
    }
    std::cin >> Q;
    std::vector<int64_t> X(Q);
    REP (i, Q) {
        std::cin >> X[i];
    }
    auto ans = solve(N, A, M, B, L, C, Q, X);
    REP (i, Q) {
        std::cout << a[i] << '\n';
    }
    return 0;
}
