#!/usr/bin/env python3
# from typing import *


# def solve(W: int, H: int, N: int, x: List[int], y: List[int], a: List[int]) -> int:
def solve(W, H, N, x, y, a):
    li = [[1 for _ in range(W)] for _ in range(H)]
    for i in range(N):
        if a[i] == 1:
            for j in range(H):
                for k in range(x[i]):
                    li[j][k] = 0
        elif a[i] == 2:
            for j in range(H):
                for k in range(x[i], W):
                    li[j][k] = 0
        elif a[i] == 3:
            for j in range(y[i]):
                for k in range(W):
                    li[j][k] = 0
        elif a[i] == 4:
            for j in range(y[i], H):
                for k in range(W):
                    li[j][k] = 0
    ans = 0
    for i in list(reversed(range(H))):
        # print(li[i])
        ans += sum(li[i])
    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    W, H, N = map(int, input().split())
    x = [None for _ in range(N)]
    y = [None for _ in range(N)]
    a = [None for _ in range(N)]
    for i in range(N):
        x[i], y[i], a[i] = map(int, input().split())
    a1 = solve(W, H, N, x, y, a)
    print(a1)

if __name__ == '__main__':
    main()
