#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


int64_t solve(int64_t a, int b, int c, const std::vector<int64_t> &d, const std::vector<int64_t> &e, const std::vector<int64_t> &f, const std::vector<int64_t> &g) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t a;
    int b, c;
    std::cin >> a >> b;
    std::vector<int64_t> f(b), g(b);
    std::cin >> c;
    std::vector<int64_t> d(c), e(c);
    REP (i, c) {
        std::cin >> d[i] >> e[i];
    }
    REP (i, b) {
        std::cin >> f[i] >> g[i];
    }
    auto ans = solve(a, b, c, d, e, f, g);
    std::cout << ans << '\n';
    return 0;
}
