#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 10)  # TODO: edit here
    T = [None for _ in range(N)]
    D = [None for _ in range(N)]
    for i in range(N):
        T[i] = random.randint(1, 5)  # TODO: edit here
        D[i] = random.randint(1, 5)  # TODO: edit here
    print(N)
    for i in range(N):
        print(T[i], D[i])

if __name__ == "__main__":
    main()
