#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


auto solve(int64_t H, int64_t W, int M, const std::vector<int64_t> &T, const std::vector<int64_t> &A, const std::vector<int64_t> &X) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t H, W;
    int M;
    std::cin >> H >> W >> M;
    std::vector<int64_t> T(M), A(M), X(M);
    REP (i, M) {
        std::cin >> T[i] >> A[i] >> X[i];
    }
    auto ans = solve(H, W, M, T, A, X);
    std::cout << n << '\n';
    REP (i, n) {
        std::cout << a[i] << ' ' << b[i] << '\n';
    }
    return 0;
}
