#!/usr/bin/env python3
# from typing import *



# def solve(X: int, Y: int, Z: int, S: str) -> int:
def solve(X, Y, Z, S):
    inf = 10000000000000
    dp = [[inf for i in range(len(S))] for i in range(2)]
    if S[0] == "A":
        dp[0][0] = min(Z + X, Z + Y)
        dp[1][0] = Y
    else:
        dp[0][0] = min(X + Z, Z + Y)
        dp[1][0] = X
    for i in range(1, len(S)):
        if S[i] == "a":
            a = dp[0][i-1] + Y
            b = dp[1][i-1] + Z + Y
            c = dp[1][i-1] + X + Z
            dp[0][i] = min(a, b, c)
            a = dp[0][i-1] + Z + X
            b = dp[0][i-1] + Y + Z
            c = dp[1][i-1] + X
            dp[1][i] = min(a, b, c)
        else:
            a = dp[0][i-1] + X
            b = dp[1][i-1] + Z + X
            c = dp[1][i-1] + Y + Z
            dp[0][i] = min(a, b, c)
            a = dp[0][i-1] + X + Z
            b = dp[0][i-1] + Z + Y
            c = dp[1][i-1] + Y
            dp[1][i] = min(a, b, c)
    # for i in dp:
    #     print(i)
    return min(dp[0][-1], dp[1][-1])




# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X, Y, Z = map(int, input().split())
    S = input()
    a = solve(X, Y, Z, S)
    print(a)

if __name__ == '__main__':
    main()
