#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(N: int, S: str, T: str) -> str:
def solve(N, S, T):
    for i in range(N):
        if S[i] != T[i]:
            if (S[i] == "0" and T[i] == "o") or (S[i] == "o" and T[i] == "0"):
                continue
            elif (S[i] == "l" and T[i] == "1") or (S[i] == "1" and T[i] == "l"):
                continue
            else:
                return NO
    return YES

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    S = input()
    T = input()
    a = solve(N, S, T)
    print(a)

if __name__ == '__main__':
    main()
